export const wordList = [
    { en: "fox", zh: "狐狸", step: 0, nextReview: 0, wrongCount: 0 },
    { en: "giraffe", zh: "长颈鹿", step: 0, nextReview: 0, wrongCount: 0 },
    { en: "eagle", zh: "雕；鹰", step: 0, nextReview: 0, wrongCount: 0 },
    { en: "wolf", zh: "狼", step: 0, nextReview: 0, wrongCount: 0 },
    { en: "penguin", zh: "企鹅", step: 0, nextReview: 0, wrongCount: 0 },
    { en: "care", zh: "照顾；护理；关心；在乎", step: 0, nextReview: 0, wrongCount: 0 },
    { en: "take care of", zh: "照顾；处理", step: 0, nextReview: 0, wrongCount: 0 },
    { en: "sandwich", zh: "三明治", step: 0, nextReview: 0, wrongCount: 0 },
    { en: "snake", zh: "蛇", step: 0, nextReview: 0, wrongCount: 0 },
    { en: "scary", zh: "吓人的；恐怖的", step: 0, nextReview: 0, wrongCount: 0 },
    { en: "neck", zh: "脖子", step: 0, nextReview: 0, wrongCount: 0 },
    { en: "guess", zh: "猜测；估计", step: 0, nextReview: 0, wrongCount: 0 },
    { en: "shark", zh: "鲨鱼", step: 0, nextReview: 0, wrongCount: 0 },
    { en: "whale", zh: "鲸", step: 0, nextReview: 0, wrongCount: 0 },
    { en: "huge", zh: "巨大的；极多的", step: 0, nextReview: 0, wrongCount: 0 },
    { en: "dangerous", zh: "危险的；有害的", step: 0, nextReview: 0, wrongCount: 0 },
    { en: "save", zh: "救；储蓄；保存", step: 0, nextReview: 0, wrongCount: 0 },
    { en: "luck", zh: "幸运；运气", step: 0, nextReview: 0, wrongCount: 0 },
    { en: "Thai", zh: "泰国的；泰国人的；泰国人；泰语", step: 0, nextReview: 0, wrongCount: 0 },
    { en: "trunk", zh: "象鼻", step: 0, nextReview: 0, wrongCount: 0 },
    { en: "pick", zh: "捡；摘", step: 0, nextReview: 0, wrongCount: 0 },
    { en: "pick up", zh: "拿起；举起", step: 0, nextReview: 0, wrongCount: 0 },
    { en: "carry", zh: "拿；提", step: 0, nextReview: 0, wrongCount: 0 },
    { en: "playful", zh: "爱嬉戏的；爱玩的", step: 0, nextReview: 0, wrongCount: 0 },
    { en: "swimmer", zh: "游泳者", step: 0, nextReview: 0, wrongCount: 0 },
    { en: "one another", zh: "互相", step: 0, nextReview: 0, wrongCount: 0 },
    { en: "look after", zh: "照顾", step: 0, nextReview: 0, wrongCount: 0 },
    { en: "culture", zh: "文化；文明", step: 0, nextReview: 0, wrongCount: 0 },
    { en: "however", zh: "然而；不过", step: 0, nextReview: 0, wrongCount: 0 },
    { en: "danger", zh: "危险", step: 0, nextReview: 0, wrongCount: 0 },
    { en: "in danger", zh: "处于危险之中", step: 0, nextReview: 0, wrongCount: 0 },
    { en: "forest", zh: "森林", step: 0, nextReview: 0, wrongCount: 0 },
    { en: "cut down", zh: "砍伐；减少", step: 0, nextReview: 0, wrongCount: 0 },
    { en: "too many", zh: "太多", step: 0, nextReview: 0, wrongCount: 0 },
    { en: "kill", zh: "杀死；弄死", step: 0, nextReview: 0, wrongCount: 0 },
    { en: "made of", zh: "由……制成的", step: 0, nextReview: 0, wrongCount: 0 },
    { en: "ivory", zh: "象牙", step: 0, nextReview: 0, wrongCount: 0 },
    { en: "friendly", zh: "友好的", step: 0, nextReview: 0, wrongCount: 0 },
    { en: "quite", zh: "相当；完全", step: 0, nextReview: 0, wrongCount: 0 },
    { en: "quite a lot", zh: "相当；非常", step: 0, nextReview: 0, wrongCount: 0 },
    { en: "not … at all", zh: "一点也不；完全不", step: 0, nextReview: 0, wrongCount: 0 },
    { en: "fur", zh: "(动物浓厚的) 软毛", step: 0, nextReview: 0, wrongCount: 0 },
    { en: "blind", zh: "瞎的；失明的", step: 0, nextReview: 0, wrongCount: 0 },
    { en: "hearing", zh: "听力；听觉", step: 0, nextReview: 0, wrongCount: 0 },
    { en: "Antarctica", zh: "南极洲", step: 0, nextReview: 0, wrongCount: 0 },
    { en: "Africa", zh: "非洲", step: 0, nextReview: 0, wrongCount: 0 },
    { en: "Malee", zh: "马莉", step: 0, nextReview: 0, wrongCount: 0 },
    { en: "Thailand", zh: "泰国", step: 0, nextReview: 0, wrongCount: 0 }
];